---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-wicked
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-wicked
  name: hello-wicked
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-wicked
  template:
    metadata:
      labels:
        app: hello-wicked
    spec:
      containers:
      - image: nginxdemo/hello:0.2
        name: hello
        ports:
        - containerPort: 80
          name: web

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-wicked
  name: hello-wicked
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hello-wicked
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-wicked
spec:
  ingressClassName: nginx
  rules:
  - host: hello-wicked.its
    http:
      paths:
      - backend:
          service:
            name: hello-wicked
            port:
              number: 80
        path: /
        pathType: Prefix

